spring:
  cache:
    type: redis
  application:
    name: exchange-data-service
  data:
    redis:
      connect-timeout: 2000
      port: 6379
      host: localhost

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

exchange:
  binance:
    base-url: https://api.binance.com/api/v3
  kraken:
    base-url: https://api.kraken.com/0/public